collections:
  theme:
   output: true
   permalink: /:name
  partner:

defaults:
  - 
    scope:
      collection: theme
    values:
      layout: "theme"

google_analytics: "UA-105013659-1"

plugins:
  - jekyll-feed

prose:
 ignore: ['_layouts', '_config.yml', 'Gemfile', 'Gemfile.lock', 'style.css', '_includes']
 siteurl: "http://olgageletina.github.io/"
 media: "img"
 metadata:
  _theme:
   - name: "issue"
     field:
      element: "text"
      label: "Issue"
   - name: "image_path"
     field: 
      element: "select"
      value: "/img/+"
      label: "Poster image"